name: Python Test Build
on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout branch main
       uses: actions/checkout@v1
       with:
        fetch-depth: 0
     - name: Setup Python 3
       uses: actions/setup-python@v2
       with:
        python-version: '3.x'
        architecture: 'x64' 
     - name: Cache deps
       uses: actions/cache@v2
       with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
     - name: Install deps
       run: pip install -r requirements.txt
     - name: Scrape
       run: python scrape.py
     - uses: actions/upload-artifact@v2
       with:
        name: Output JSON
        path: data.json
